module.exports = {
    "en-GB": {
        "translation": {
            "THERE_IS": "There is",
            "EVENT": "event",
            "THERE_ARE": "There are",
            "EVENTS": "events",
            "ON_AT": "on at",
            "PARLIAMENT": "the Houses of Parliament",
            "TODAY": "today:",
            "IN": "in",
            "THE_COMMONS": "the House of Commons",
            "STARTING_AT": "starting at",
            "AND": "and",
            "THE_LORDS": "the House of Lords",
            "HEAR_MORE": ". Would you like to hear more?",
            "IT_IS": "it is",
            "THEY_ARE": "they are all",
            "NO_EVENTS": "There are no events",
            "WHATS_ON_CARD_TITLE": "What's on at Parliament",
            "WHATS_ON_ERROR": "There was an error finding out what's on. Please try again later.",
            "HELP_TEXT": "You can say 'what's on at the houses of parliament', or, you can say exit... What can I help you with?",
            "HELP_TEXT_REPROMPT": "You can say 'what's on at the houses of parliament', or, you can say exit... What can I help you with?",
            "LAUNCH_TEXT": "UK Parliament. You can find out what’s on in: the House of Commons, the House of Lords, or the Houses of Parliament. Which would you like to do?",
            "YES_RESPONSE": "Once this feature has been implemented, it will be great!",
            "NO_RESPONSE": "Okay",
            "CANCEL_RESPONSE": "",
            "ERROR": "Something went wrong, please try again later",
            "REQUEST_ERROR": "There was a problem connecting to Parliament. Please try again later.",
            "FROM": "From",
            "TILL": "till",
            "THATS_ALL": "That's all for today."
        }
    },
    "en-US": {
        "translation": {
            "THERE_IS": "There is",
            "EVENT": "event",
            "THERE_ARE": "There are",
            "EVENTS": "events",
            "ON_AT": "on at",
            "PARLIAMENT": "the Houses of Parliament",
            "TODAY": "today:",
            "IN": "in",
            "THE_COMMONS": "the House of Commons",
            "STARTING_AT": "starting at",
            "AND": "and",
            "THE_LORDS": "the House of Lords",
            "HEAR_MORE": ". Would you like to hear more?",
            "IT_IS": "it is",
            "THEY_ARE": "they are all",
            "NO_EVENTS": "There are no events",
            "WHATS_ON_CARD_TITLE": "What's on at Parliament",
            "WHATS_ON_ERROR": "There was an error finding out what's on. Please try again later.",
            "HELP_TEXT": "You can say 'what's on at the houses of parliament', or, you can say exit... What can I help you with?",
            "HELP_TEXT_REPROMPT": "You can say 'what's on at the houses of parliament', or, you can say exit... What can I help you with?",
            "LAUNCH_TEXT": "UK Parliament. You can find out what’s on in: the House of Commons, the House of Lords, or the Houses of Parliament. Which would you like to do?",
            "YES_RESPONSE": "Once this feature has been implemented, it will be great!",
            "NO_RESPONSE": "Okay",
            "CANCEL_RESPONSE": "",
            "ERROR": "Something went wrong, please try again later",
            "REQUEST_ERROR": "There was a problem connecting to Parliament. Please try again later.",
            "FROM": "From",
            "TILL": "till",
            "THATS_ALL": "That's all for today."
        }
    }
};
